version: '3.7'
x-environment: &env
  PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
  REDASH_COOKIE_SECRET: MUST_SET
  REDASH_DATABASE_URL: postgres://redash:redash@postgres:5432/redashdb
  REDASH_HOST: ${REDASH_HOST}
  REDASH_LOG_LEVEL: INFO
  REDASH_MAIL_DEFAULT_SENDER: ${REDASH_MAIL_DEFAULT_SENDER}
  REDASH_MAIL_PASSWORD: ${REDASH_MAIL_PASSWORD}
  REDASH_MAIL_SERVER: ${REDASH_MAIL_SERVER}
  REDASH_MAIL_USERNAME: ${REDASH_MAIL_USERNAME}
  REDASH_REDIS_URL: redis://redis:6379/0
services:
  web:
    image: redash/redash:8.0.2.b37747
    ports:
      - 5001:5000
    environment:
      <<: *env
      REDASH_MAIL_PORT: 25
      REDASH_WEB_WORKERS: 4
    command: server
    links:
      - redis
      - postgres
  scheduler:
    image: redash/redash:8.0.2.b37747
    command: scheduler
    environment:
      <<: *env
      QUEUES: queries,scheduled_queries,celery
      WORKERS_COUNT: 2
    links:
      - redis
      - postgres
  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6380:6379
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: 'redash'
      POSTGRES_PASSWORD: 'redash'
      POSTGRES_DB: 'redashdb'
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: {}